import type { Metadata } from "next";
import { Geist, Geist_Mono, Source_Sans_3 } from "next/font/google";
import "./globals.css";

const geistSource = Source_Sans_3({
  variable: "--font-source_sans_3",
  subsets: ["latin"],
  display: "swap", // optional, helps with performance
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSource.variable} antialiased`}>{children}</body>
    </html>
  );
}
